### ISSUE TITLE
Save button should be desabled or hidden if there is nothing to save

### ISSUE THREAD

**Issue by vasily-kirichenko** [magicmonty/volca-fm-editor#1]
![1](https://user-images.githubusercontent.com/873919/33803136-9a08c2f8-dd99-11e7-88a8-59114f94709e.gif)

I think the button should be disabled over here:

https://github.com/magicmonty/volca-fm-editor/blob/a4de9fed76e0ff284369bf8f1b9ed86d1f738e7e/src/State.fs#L494

**Comment by magicmonty** [comment]
Oh yeah, missed that. Thanks
